### ISSUE TITLE
SVE512, Eltwise unit tests broke

### ISSUE THREAD

**Issue by breuera** [libxsmm/libxsmm#700]
Looks like the SVE512 CI broke with commit [89ab649](https://github.com/libxsmm/libxsmm/commit/89ab649cfe940d8786deaf3efbf7ed58e4707c64) which is the 256 merge.
[cb794de](https://github.com/libxsmm/libxsmm/commit/cb794deb73934da37efc27f9d4816a57b3b533f5) was the last commit which passed.
ASIMD tests are passing.

Anyone aware of issues?
Otherwise I can look into this.

Here's what's being executed on A64FX:

```
steps:
  - command:
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - cd samples/eltwise/
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - ./run_test_aarch64_sve.sh
      - cd ../..
    label: ":pipeline: eltwise"
    agents:
      isa: "sve512"
  - command:
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - cd samples/xgemm
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - export LIBXSMM_TARGET=a64fx
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/sgemm_tn_eqld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/dgemm_tn_eqld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/dgemm_tn_gtld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/sgemm_tn_gtld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/sgemm_nn_eqld.slurm\n"

      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/dgemm_nt_eqld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/dgemm_nn_eqld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/sgemm_nn_gtld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/sgemm_nt_eqld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/sgemm_nt_gtld.slurm\n"

      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/dgemm_nt_gtld.slurm\n"
      - export XSMM_TESTS="\${XSMM_TESTS} kernel_test/dgemm_nn_gtld.slurm\n"
      - echo \${XSMM_TESTS}
      - echo -e \${XSMM_TESTS}
      - echo -e \${XSMM_TESTS} | ../../scripts/tool_pexec.sh -c 3- "$@"
      - cd ../..
    label: ":pipeline: xgemm"
    agents:
      isa: "sve512"
```

This is the output:

```
[...]
gcc -dynamic -o eltwise_unary_transform obj/eltwise_unary_transform-c.o -L/hkfs/home/project/hk-project-test-scalfsu/hgf_prd6221/buildkite/builds/ftp-a64n1/edge/libxsmm-sve512/lib ../../lib/libxsmm.a -L/hkfs/home/project/hk-project-test-scalfsu/hgf_prd6221/buildkite/builds/ftp-a64n1/edge/libxsmm-sve512/lib ../../lib/libxsmmnoblas.a  -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--export-dynamic -Wl,--as-needed -lm -lrt -ldl -Wl,--no-as-needed -fopenmp -Wl,--as-needed -lstdc++ -Wl,--no-as-needed -pthread
--
  | Execute PIPELINE-ELTWISE with NTASKS=62, NPROCS=48, and OMP_NUM_THREADS=1
  | -> ERROR[001]: binary_div_eqld
  | -> ERROR[001]: unary_dropout_gtld_65
  | -> ERROR[001]: unary_dropout_eqld_65
  | -> ERROR[001]: binary_div_gtld
  | -> VALID[000]: unary_trans_64b_gtld
  | -> VALID[000]: unary_trans_32b_eqld
  | -> VALID[000]: unary_trans_64b_eqld
  | -> VALID[000]: unary_trans_32b_gtld
[...]
-> VALID[000]: unary_sigmoid_inv_eqld
--
  | -> VALID[000]: unary_sigmoid_gtld
  | --------------------------------------------------------------------------------
  | 🚨 Error: The command exited with status 123
  | user command error: exit status 123
```
