### ISSUE TITLE
ASIMD: Element-wise tests are failing

### ISSUE THREAD

**Issue by breuera** [libxsmm/libxsmm#735]
The element-wise tests are failing when using N1.
Last successful run was on January 10 ([03f0e9c](https://github.com/libxsmm/libxsmm/commit/03f0e9c27cfb17e24ffe9d2d88ceaf3d2c3aaf88)).

This is the pipeline:

```
steps:
  - command:
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - cd samples/eltwise/
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - ./run_test.sh
      - cd ../..
    label: ":pipeline: eltwise"
```

Here's the output:
[0185cdc7-2fee-4482-9bfb-887fbc12a090.log](https://github.com/libxsmm/libxsmm/files/10465870/0185cdc7-2fee-4482-9bfb-887fbc12a090.log)
